on:
  workflow_dispatch:

jobs:
  
  build:
    name: Build
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        architecture: [x64]
        configuration: [Release]

    steps:
    - uses: actions/checkout@v2

    - name: Gather environment info
      run: npx envinfo

    - name: Yarn install
      run: yarn install

    - name: Run react-native run-windows
      run: npx react-native run-windows --logging --no-packager --no-launch --arch ${{ matrix.architecture }} ${{ startsWith(matrix.architecture, 'ARM') && '--no-deploy' || '' }} ${{ matrix.configuration == 'Release' && '--release' || '' }}

#    - name: Setup Node.js
#      uses: actions/setup-node@v1
#      with:
#        node-version: '14'
#
#    - name: Setup MSBuild
#      uses: microsoft/setup-msbuild@v1.0.2
#      with:
#        vs-version: 16.8
#
#    - name: Install node modules
#      run: yarn --frozen-lockfile
#
#    - name: yarn build
#      run:  yarn build
